import type { Category, Globals, HeroSlide, Product } from "@/types";

export const mockGlobals: Globals = {
  brandName: "Дело вкуса",
  legalName: "ООО «Дело вкуса»",
  inn: "1650000000",

  aboutShort:
    "Пекарня, кулинария и собственное производство в Корсакове с 2013 года. Свежая выпечка каждое утро, домашняя кухня и полуфабрикаты ручной лепки.",
  aboutLong:
    "«Дело вкуса» — мультиформатная гастрономическая платформа, объединяющая три направления: ремесленную пекарню и кондитерскую, горячую кулинарию (курица гриль, шаурма, готовые обеды) и собственное производство замороженных полуфабрикатов. Мы печём хлеб на собственной закваске, делаем сытную и сладкую выпечку по проверенным рецептам, готовим горячие блюда и лепим пельмени, вареники и манты вручную.",
  productionMd:
    "Ежедневная пекарня работает с 04:00, лепка полуфабрикатов — круглосуточно. Всё оборудование сертифицировано, процессы проходят ежедневный контроль качества.",
  careersMd:
    "Мы всегда рады талантливым пекарям, кондитерам и продавцам. Пишите нам — расскажем об открытых позициях.",

  aboutPageTitle: "О компании",
  productionHeading: "Производство",
  careersHeading: "Вакансии",
  careersEmailIntro: "Пишите на",
  innLabel: "ИНН",

  social: {
    vk: "https://vk.com/delovkusa",
    telegram: "https://t.me/delovkusa",
    instagram: "https://instagram.com/delovkusa",
  },
  appLinks: {
    appStore: "#",
    googlePlay: "#",
    ruStore: "#",
  },

  emailGeneral: "hello@delovkusa.ru",
  emailHr: "hr@delovkusa.ru",
  emailB2b: "b2b@delovkusa.ru",

  taglineMain: "Свежая выпечка",
  taglineAccent: "каждый день",

  metaTitle: "Дело вкуса — свежая выпечка каждый день",
  metaDescription:
    "Ремесленная пекарня и собственное производство в Корсакове: хлеб, сытная и сладкая выпечка, курица гриль, шаурма и полуфабрикаты ручной лепки.",
  seoKeywords: [
    "пекарня корсаков",
    "свежая выпечка",
    "хлеб корсаков",
    "курица гриль",
    "шаурма корсаков",
    "пельмени ручной лепки",
    "самовывоз выпечка",
    "дело вкуса",
  ],

  themeColor: "#d62929",
  backgroundColor: "#eae6e1",
  paymentMethods: ["МИР", "Visa", "Mastercard", "СБП"],

  opensAt: "08:00",
  closesAt: "20:00",
};

export const mockHeroSlides: HeroSlide[] = [
  {
    id: "h1",
    title: "Свежая выпечка",
    accent: "каждый день",
    description: "Готовим с душой из натуральных ингредиентов и по проверенным рецептам",
    image: "/sliders/bread.webp",
    cta: { label: "Перейти в каталог", href: "/catalog" },
  },
  {
    id: "h2",
    title: "Тёплая самса",
    accent: "из печи",
    description: "Слоёное тесто, сочная начинка — забирайте горячей через 15 минут после заказа",
    image: "/sliders/savory-pastry.webp",
    cta: { label: "Смотреть выпечку", href: "/catalog/savory-pastry" },
  },
  {
    id: "h3",
    title: "Полуфабрикаты",
    accent: "как дома",
    description: "Пельмени, вареники и манты ручной лепки — наша гордость в каждой упаковке",
    image: "/sliders/frozen.webp",
    cta: { label: "Заморозка", href: "/catalog/frozen" },
  },
  {
    id: "h4",
    title: "Сладкая сдоба",
    accent: "с маком",
    description: "Свежие булочки, ватрушки и рулеты — идеальная пара к утреннему кофе",
    image: "/sliders/sweet-pastry.webp",
    cta: { label: "Сладкая выпечка", href: "/catalog/sweet-pastry" },
  },
  {
    id: "h5",
    title: "Напитки",
    accent: "к любому блюду",
    description: "Натуральные лимонады, компоты и чай — всё, что освежит ваш день",
    image: "/sliders/drinks.webp",
    cta: { label: "К напиткам", href: "/catalog/drinks" },
  },
];

export const mockProducts: Product[] = [
  // Хлеб
  {
    id: "p1",
    slug: "bread-loaf",
    title: "Хлеб «Домашний»",
    categorySlug: "bread",
    image: "/products/bread-loaf.webp",
    price: 65,
    weight: "450 г",
    tag: "hit",
    available: true,
    description: "Формовой хлеб на пшеничной муке первого сорта, без улучшителей и консервантов.",
  },

  // Сытная выпечка
  {
    id: "p2",
    slug: "echpochmak",
    title: "Эчпочмак (Самса)",
    categorySlug: "savory-pastry",
    image: "/products/echpochmak.webp",
    price: 75,
    weight: "120 г",
    available: true,
    description: "Треугольник с мясом и картофелем, запечённый в слоёном тесте.",
  },
  {
    id: "p3",
    slug: "mini-pizza",
    title: "Мини-пицца «Школьная»",
    categorySlug: "savory-pastry",
    image: "/products/mini-pizza.webp",
    price: 95,
    weight: "120 г",
    available: true,
    description: "Любимая школьная пицца: томатный соус, колбаса, сыр.",
  },
  {
    id: "p4",
    slug: "cheburek",
    title: "Чебурек с говядиной",
    categorySlug: "savory-pastry",
    image: "/products/cheburek.webp",
    price: 110,
    weight: "150 г",
    tag: "hit",
    available: true,
    description: "Тонкое тесто, сочная начинка из рубленой говядины с луком.",
  },
  {
    id: "p5",
    slug: "belyash",
    title: "Беляш с мясом",
    categorySlug: "savory-pastry",
    image: "/products/belyash.webp",
    price: 85,
    weight: "130 г",
    available: true,
    description: "Жаренный во фритюре беляш с рубленой говядиной.",
  },
  {
    id: "p6",
    slug: "big-closed-pie",
    title: "Большой закрытый пирог",
    categorySlug: "savory-pastry",
    image: "/products/big-closed-pie.webp",
    price: 520,
    weight: "900 г",
    available: true,
    description: "Большой семейный пирог с начинкой на выбор.",
  },
  {
    id: "p7",
    slug: "fried-flatbread",
    title: "Жареная лепёшка",
    categorySlug: "savory-pastry",
    image: "/products/fried-flatbread.webp",
    price: 60,
    weight: "110 г",
    available: true,
  },
  {
    id: "p8",
    slug: "savory-pies",
    title: "Пирожки несладкие",
    categorySlug: "savory-pastry",
    image: "/products/savory-pies.webp",
    price: 55,
    weight: "90 г",
    available: true,
    description: "Пирожки ассорти: картошка, капуста, яйцо с луком.",
  },
  {
    id: "p9",
    slug: "tvorog-triangle",
    title: "Треугольный пирожок с творогом",
    categorySlug: "savory-pastry",
    image: "/products/tvorog-triangle.webp",
    price: 70,
    weight: "100 г",
    available: true,
    description: "Открытый треугольник с нежным творогом и сметанной заливкой.",
  },

  // Сладкая выпечка
  {
    id: "p10",
    slug: "poppy-buns",
    title: "Сдобный узел с маком",
    categorySlug: "sweet-pastry",
    image: "/products/poppy-buns.webp",
    price: 55,
    weight: "120 г",
    tag: "new",
    available: true,
    description: "Мягкая сдоба с маковой начинкой, посыпанная сахарной пудрой.",
  },
  {
    id: "p11",
    slug: "vatrushka",
    title: "Ватрушка с творогом",
    categorySlug: "sweet-pastry",
    image: "/products/vatrushka.webp",
    price: 70,
    weight: "100 г",
    available: true,
    description: "Сдоба с ванильным творогом и сахарной пудрой.",
  },
  {
    id: "p12",
    slug: "poppy-roll",
    title: "Рулет с маком",
    categorySlug: "sweet-pastry",
    image: "/products/poppy-roll.webp",
    price: 140,
    weight: "300 г",
    available: true,
    description: "Сдобный рулет с маковой начинкой.",
  },
  {
    id: "p13",
    slug: "figured-buns",
    title: "Фигурные булочки",
    categorySlug: "sweet-pastry",
    image: "/products/figured-buns.webp",
    price: 45,
    weight: "80 г",
    available: true,
    description: "Сдобные булочки-косички с ванилью.",
  },
  {
    id: "p14",
    slug: "sweet-pie",
    title: "Сладкий пирожок",
    categorySlug: "sweet-pastry",
    image: "/products/sweet-pie.webp",
    price: 50,
    weight: "90 г",
    available: true,
    description: "Пирожок с яблочной или вишнёвой начинкой, сахарная пудра.",
  },
  {
    id: "p15",
    slug: "plain-bun",
    title: "Булочка без начинки",
    categorySlug: "sweet-pastry",
    image: "/products/plain-bun.webp",
    price: 35,
    weight: "70 г",
    available: true,
    description: "Классическая сдобная булочка к чаю.",
  },

  // Готовые блюда
  {
    id: "p16",
    slug: "grill-chicken",
    title: "Курица гриль",
    categorySlug: "ready-meals",
    image: "/products/grill-chicken.webp",
    price: 450,
    weight: "1.2 кг",
    tag: "hit",
    available: true,
    description: "Фермерская курица в фирменном маринаде. Подаётся горячей.",
  },
  {
    id: "p17",
    slug: "shaurma",
    title: "Шаурма «Классик»",
    categorySlug: "ready-meals",
    image: "/products/shaurma.webp",
    price: 220,
    weight: "320 г",
    available: true,
    description: "Лаваш, курица гриль, овощи, фирменный соус.",
  },

  // Полуфабрикаты
  {
    id: "p18",
    slug: "frozen-pelmeni",
    title: "Пельмени ручной лепки",
    categorySlug: "frozen",
    image: "/products/frozen-pelmeni.webp",
    price: 320,
    weight: "500 г",
    available: true,
    description: "Классические пельмени, начинка — свинина с говядиной. Ручная лепка.",
  },
  {
    id: "p19",
    slug: "frozen-vareniki",
    title: "Вареники с вишней",
    categorySlug: "frozen",
    image: "/products/frozen-vareniki.webp",
    price: 280,
    weight: "500 г",
    tag: "new",
    available: true,
    description: "Сладкие вареники с вишневой начинкой без сахара.",
  },
  {
    id: "p20",
    slug: "frozen-pies",
    title: "Замороженные пирожки",
    categorySlug: "frozen",
    image: "/products/frozen-pies.webp",
    price: 220,
    weight: "400 г",
    available: true,
    description: "Полуфабрикаты для выпечки дома: картофель, капуста, мясо.",
  },
  {
    id: "p21",
    slug: "frozen-buns",
    title: "Замороженные булочки",
    categorySlug: "frozen",
    image: "/products/frozen-buns.webp",
    price: 180,
    weight: "360 г",
    available: true,
    description: "Сдоба в заморозке: дома осталось только разогреть.",
  },
  {
    id: "p22",
    slug: "dough-balls",
    title: "Заготовки теста",
    categorySlug: "frozen",
    image: "/products/dough-balls.webp",
    price: 140,
    weight: "500 г",
    available: true,
    description: "Шарики дрожжевого теста на любой выпечки.",
  },

  // Напитки
  {
    id: "p23",
    slug: "drinks-set",
    title: "Лимонад «Тархун»",
    categorySlug: "drinks",
    image: "/products/drinks-set.webp",
    price: 120,
    weight: "0.5 л",
    available: true,
    description: "Натуральный лимонад без красителей.",
  },
];

export const mockCategories: Category[] = [
  {
    id: "c1",
    slug: "bread",
    title: "Хлеб",
    subtitle: "Ремесленный каждый день",
    image: "/categories/bread.webp",
    sliderImage: "/sliders/bread.webp",
    productsCount: mockProducts.filter((p) => p.categorySlug === "bread").length,
  },
  {
    id: "c2",
    slug: "savory-pastry",
    title: "Сытная выпечка",
    subtitle: "Пирожки, чебуреки, беляши",
    image: "/categories/savory-pastry.webp",
    sliderImage: "/sliders/savory-pastry.webp",
    productsCount: mockProducts.filter((p) => p.categorySlug === "savory-pastry").length,
  },
  {
    id: "c3",
    slug: "sweet-pastry",
    title: "Сладкая выпечка",
    subtitle: "Сдоба с маком и творогом",
    image: "/categories/sweet-pastry.webp",
    sliderImage: "/sliders/sweet-pastry.webp",
    productsCount: mockProducts.filter((p) => p.categorySlug === "sweet-pastry").length,
  },
  {
    id: "c4",
    slug: "ready-meals",
    title: "Готовые блюда",
    subtitle: "Гриль, шаурма, обеды",
    image: "/categories/ready-meals.webp",
    productsCount: mockProducts.filter((p) => p.categorySlug === "ready-meals").length,
  },
  {
    id: "c5",
    slug: "frozen",
    title: "Полуфабрикаты",
    subtitle: "Ручная лепка",
    image: "/categories/frozen.webp",
    sliderImage: "/sliders/frozen.webp",
    productsCount: mockProducts.filter((p) => p.categorySlug === "frozen").length,
  },
  {
    id: "c6",
    slug: "drinks",
    title: "Напитки",
    subtitle: "Соки, лимонады, чай",
    image: "/categories/drinks.webp",
    sliderImage: "/sliders/drinks.webp",
    productsCount: mockProducts.filter((p) => p.categorySlug === "drinks").length,
  },
];

